// // Scripted pipeline
// node{
//     stage('preapration'){
//         echo 'Cloning the repository'
//         git url:'https://github.com/Muhammadasim225/simple-node-project',branch:'main'
//     }
//     stage('image'){
//         echo 'Builing Image'
//         sh 'docker build -t muhammadasim0333/nodejs_dummy:${BUILD_NUMBER} .'
       
//     }
//     stage("Deplyo to dockerhub"){
//         withCredentials([usernamePassword(credentialsId: 'dockerhubcred', usernameVariable: 'USERNAME_DOC', passwordVariable: 'PASSWORD_DOC')]) {
 
//             sh 'docker login -u ${USERNAME_DOC} -p ${PASSWORD_DOC}'
//             sh 'docker image push muhammadasim0333/nodejs_dummy:${BUILD_NUMBER}'
// }
//     }
//     stage("Clean Up"){
//         sh 'docker logout'
//     }
// }

// Declarative Jenkinsfile

pipeline {
    agent any
    environment{
        IMAGE_NAME = "muhammadasim0333/nodejs_dummy"
        scannerHome=tool 'SonarScanner'
    }


    stages {

        stage('Preparation') {
            steps {
                echo 'Cloning the repository'
                git branch: 'main', url: 'https://github.com/Muhammadasim225/simple-node-project'
            }
        }

         stage('SonarQube Analysis') {
            steps{
                withSonarQubeEnv() {
                sh "${scannerHome}/bin/sonar-scanner"
                }

            }
            
            }

        stage('Build Image') {
            steps {
                echo 'Building Docker Image'
                sh "docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} ."
            }
        }

        stage('Deploy to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhubcred',
                    usernameVariable: 'USERNAME_DOC',
                    passwordVariable: 'PASSWORD_DOC'
                )]) {
                    sh "docker login -u ${USERNAME_DOC} -p ${PASSWORD_DOC}"
                    sh "docker push ${IMAGE_NAME}:${BUILD_NUMBER}"
                }
            }
        }

        stage('Clean Up') {
            steps {
                sh 'docker logout'
            }
        }
    }
}